package rc2server;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class RC2Server extends javax.swing.JFrame {
    
    DefaultTableModel tabmod4Buku = new DefaultTableModel();
    private Connection konek;
    ServerConn servConn;
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public RC2Server() throws Exception {
        Class.forName("com.mysql.jdbc.Driver");
        konek = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/rc2database", "root", "");
        
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        servConn = new ServerConn(this);
        DBConn.setConnection();
        
        conn = MySQLConnection.ConnectDB();
        updateTable();
    }
    
    private void updateTable() {
        try {
            String sql = "SELECT * FROM BUKU";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tblBuku.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIDBuku = new javax.swing.JLabel();
        tfPenerbit = new javax.swing.JTextField();
        lblGenreBuku = new javax.swing.JLabel();
        tfRak = new javax.swing.JTextField();
        lblNamaBuku = new javax.swing.JLabel();
        tfStok = new javax.swing.JTextField();
        lblPengarang = new javax.swing.JLabel();
        btnInsert = new javax.swing.JToggleButton();
        lblPenerbit = new javax.swing.JLabel();
        tfHargaBuku = new javax.swing.JTextField();
        lblRak = new javax.swing.JLabel();
        lblStok1 = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        btnSearch = new javax.swing.JToggleButton();
        tfIDBuku = new javax.swing.JTextField();
        btnDelete = new javax.swing.JToggleButton();
        tfGenreBuku = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JToggleButton();
        tfNamaBuku = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        tfPengarang = new javax.swing.JTextField();
        tfSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIDBuku.setText("ID");

        lblGenreBuku.setText("GENRE");

        lblNamaBuku.setText("NAMA");

        lblPengarang.setText("PENGARANG");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        lblPenerbit.setText("PENERBIT");

        lblRak.setText("RAK");

        lblStok1.setText("HARGA");

        lblStok.setText("STOK");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsert)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenreBuku)
                            .addComponent(lblIDBuku)
                            .addComponent(lblNamaBuku)
                            .addComponent(lblPengarang)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfRak, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(tfPenerbit)
                                    .addComponent(tfPengarang)
                                    .addComponent(tfNamaBuku)
                                    .addComponent(tfGenreBuku)
                                    .addComponent(tfIDBuku)
                                    .addComponent(tfHargaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblStok)
                            .addComponent(lblRak)
                            .addComponent(lblPenerbit)
                            .addComponent(lblStok1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDBuku)
                            .addComponent(tfIDBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGenreBuku)
                            .addComponent(tfGenreBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamaBuku)
                            .addComponent(tfNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPengarang)
                            .addComponent(tfPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPenerbit)
                            .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRak)
                            .addComponent(tfRak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStok)
                            .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStok1)
                    .addComponent(tfHargaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnSearch)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//------------------------------------------------------------------------------
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            insertBuku(tfGenreBuku.getText(), tfNamaBuku.getText(), tfPengarang.getText(),
                    tfPenerbit.getText(), Integer.parseInt(tfRak.getText()), Integer.parseInt(tfStok.getText()),
                    Integer.parseInt(tfHargaBuku.getText()));
        } catch (Exception ex) {
            Logger.getLogger(RC2Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertActionPerformed
//------------------------------------------------------------------------------
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            searchBuku(tfSearch.getText());
            /*String query = "SELECT * FROM BUKU WHERE ID_BUKU = ? OR NAMA_BUKU = ";
            PreparedStatement pst = konek.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            tblBuku.setModel(DbUtils.resultSetToTableModel(rs));*/
        } catch (SQLException ex) {
            Logger.getLogger(RC2Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

//------------------------------------------------------------------------------
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            deleteBuku(Integer.parseInt(tfIDBuku.getText()));
        } catch (Exception ex) {
            Logger.getLogger(RC2Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

//------------------------------------------------------------------------------
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            updateBuku(Integer.parseInt(tfIDBuku.getText()), tfGenreBuku.getText(), tfNamaBuku.getText(), tfPengarang.getText(),
                    tfPenerbit.getText(), Integer.parseInt(tfRak.getText()), Integer.parseInt(tfStok.getText()),
                    Integer.parseInt(tfHargaBuku.getText()));
        } catch (Exception ex) {
            Logger.getLogger(RC2Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        int selectedRowIndex = tblBuku.getSelectedRow();
            tfIDBuku.setText(tblBuku.getValueAt(selectedRowIndex, 0).toString());
            tfGenreBuku.setText(tblBuku.getValueAt(selectedRowIndex, 1).toString());
            tfNamaBuku.setText(tblBuku.getValueAt(selectedRowIndex, 2).toString());
            tfPengarang.setText(tblBuku.getValueAt(selectedRowIndex, 3).toString());
            tfPenerbit.setText(tblBuku.getValueAt(selectedRowIndex, 4).toString());
            tfRak.setText(tblBuku.getValueAt(selectedRowIndex, 5).toString());
            tfStok.setText(tblBuku.getValueAt(selectedRowIndex, 6).toString());
            tfHargaBuku.setText(tblBuku.getValueAt(selectedRowIndex, 7).toString());              
    }//GEN-LAST:event_tblBukuMouseClicked
    
    public void insertBuku (String genreBuku, String namaBuku, String pengarang, String penerbit,
            int rak, int stok, int hargaBuku) throws SQLException {
        String query = "INSERT INTO BUKU (GENRE_BUKU, NAMA_BUKU, PENGARANG, PENERBIT, RAK, STOK, HARGA_BUKU) VALUES(?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement stmt = konek.prepareStatement(query);
        stmt.setString(1, genreBuku);
        stmt.setString(2, namaBuku);
        stmt.setString(3, pengarang);
        stmt.setString(4, penerbit);
        stmt.setInt(5, rak);
        stmt.setInt(6, stok);
        stmt.setInt(7, hargaBuku);
        stmt.execute();
        stmt.close();
    }
    
    public void updateBuku (int idBuku, String genreBuku, String namaBuku, String pengarang, String penerbit,
            int rak, int stok, int hargaBuku) throws SQLException {
        String query = "UPDATE BUKU SET GENRE_BUKU = ?, NAMA_BUKU = ?, PENGARANG = ?, PENERBIT = ?, RAK = ?, STOK = ?, HARGA_BUKU = ? WHERE ID_BUKU = ?";
        PreparedStatement stmt = konek.prepareStatement(query);
        stmt.setString(1, genreBuku);
        stmt.setString(2, namaBuku);
        stmt.setString(3, pengarang);
        stmt.setString(4, penerbit);
        stmt.setInt(5, rak);
        stmt.setInt(6, stok);
        stmt.setInt(7, hargaBuku);
        stmt.setInt(8, idBuku);
        stmt.execute();
        stmt.close();
    }
    
    public void deleteBuku (int idBuku) throws SQLException {
        String query = "DELETE FROM BUKU WHERE ID_BUKU = ?";
        PreparedStatement stmt = konek.prepareStatement(query);
        stmt.setInt(1, idBuku);
        stmt.execute();
        stmt.close();
    }
    
    public void searchBuku (String param) throws SQLException {
        String query = "SELECT * FROM BUKU WHERE ID_BUKU LIKE '%" + param + "%' OR GENRE_BUKU LIKE '%" + param 
                + "%' OR NAMA_BUKU LIKE '%" + param + "%' OR PENGARANG LIKE '%" + param + "%' OR PENERBIT LIKE '%" 
                + param + "%' OR HARGA_BUKU LIKE '%" + param + "%' OR RAK LIKE '%" + param 
                + "%' OR STOK LIKE '%" + param + "%'";
        PreparedStatement stmt = konek.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();
        tblBuku.setModel(DbUtils.resultSetToTableModel(rs));
        //stmt.setInt(1, idBuku);
        //stmt.setString(2, namaBuku);
        /*String query = "SELECT * FROM BUKU WHERE ID_BUKU = ? OR NAMA_BUKU = ";
            PreparedStatement pst = konek.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            tblBuku.setModel(DbUtils.resultSetToTableModel(rs));*/
        stmt.execute();
        stmt.close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RC2Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RC2Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RC2Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RC2Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RC2Server().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(RC2Server.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDelete;
    private javax.swing.JToggleButton btnInsert;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JToggleButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGenreBuku;
    private javax.swing.JLabel lblIDBuku;
    private javax.swing.JLabel lblNamaBuku;
    private javax.swing.JLabel lblPenerbit;
    private javax.swing.JLabel lblPengarang;
    private javax.swing.JLabel lblRak;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblStok1;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField tfGenreBuku;
    private javax.swing.JTextField tfHargaBuku;
    private javax.swing.JTextField tfIDBuku;
    private javax.swing.JTextField tfNamaBuku;
    private javax.swing.JTextField tfPenerbit;
    private javax.swing.JTextField tfPengarang;
    private javax.swing.JTextField tfRak;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfStok;
    // End of variables declaration//GEN-END:variables
}
